import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from './_components/navbar';
import { Footer } from './_components/footer';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Gym Pro',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl'>
			<body className={`${inter.className} bg-steel-gradient`}>
				<ClerkProvider>
					<Navbar />
					{children}
					<Footer />
				</ClerkProvider>
			</body>
		</html>
	);
}
